### PR TITLE
Update UMFPACK support

### PR DESCRIPTION
**Pull request by wo80**
UMFPACK is now called using function templates wrapping the `umfpack_di_*` and `umfpack_zi_*` methods. This should also be easily extendable, in case UMFPACK should provide single precision methods one day.

I have added a sparse matrix class in https://github.com/m-reuter/arpackpp/commit/40c58b9a1f1433d915624ca427a1297c8201c174 . It is not meant to be a general purpose matrix class, but provides optimized methods for computing `A+s*B` or expanding symmetric matrices. Those were responsible for a lot of code duplication between the sparse matrix solvers arpackpp provides (SuperLU, CHOLMOD, UMFPACK), so adding this new class should make the implementation of the matrix and pencil classes easier. SuperLU and CHOLMOD are the next to be addressed, in case this gets merged.

Please review carefully.

### CODE REVIEW

**Comment by m-reuter** [comment]
Thanks, I carefully looked through the changes and it looks great. Makes it definitely more clear. Thanks.

**Comment by wo80** [comment]
> Thanks, I carefully looked through the changes and it looks great. Makes it definitely more clear. Thanks.

Thanks for merging! I'm still not happy with the constructor arguments. Having the `bool check = true` as an argument, doesn't make much sense to me. I think it should be fair to assume that the arrays passed in the constructor contain valid matrix data, so I'd suggest to remove that argument and always run the check. Also, rearranging the arguments as I did changes the public API:

Before:
```c++
  ARumNonSymMatrix(int np, int nnzp, ARTYPE* ap, int* irowp, int* pcolp,
                  double thresholdp = 0.1, bool check = true);
```

Now:
```c++
  ARumNonSymMatrix(int np, int nnzp, ARTYPE* ap, int* irowp, int* pcolp,
                   bool check = true, double thresholdp = 0.1);
```

Suggestion:
```c++
  ARumNonSymMatrix(int np, int nnzp, ARTYPE* ap, int* irowp, int* pcolp,
                   double thresholdp = 0.1);
```

What do you think?

**Comment by m-reuter** [comment]
Yes, I missed that. Would be better to not change the public API. But that would mean to keep check as the last argument.

Why would someone set check to false? What is the overhead (time/computation) of always performing the test? If that is small, I am fine with dropping that argument and always checking. It is a small API change, and we'd probably need to do a major release then next time as it could break existing code where check is passed.

**Comment by wo80** [comment]
The `Check` method has no significant overhead, it's _O(number of nonzeros)_. It validates the compressed column storage, see https://github.com/m-reuter/arpackpp/blob/5136363cb87d0f59438e564fa444d6d5f0fd1d46/include/arspmat.h#L221

In my last commit https://github.com/m-reuter/arpackpp/pull/31/commits/2f0fc72377660433625540fb34ecda4ef79b6ad4 I fixed a problem where the argument had to be set to `false`, since the arrays were allocated, but not initialized to zeros (so the column pointers array contained random values, which made the check method fail). This is the only use-case I can think of, and I find it very unlikely to occur for a user of arpackpp (the fix would be as easy as `std::fill(pcol, pcol + ncols + 1, 0)`, which represents an empty matrix and is always valid).

So I'm still in favor of dropping the argument (also from the other sparse solvers). And you're right, in case arpackpp should conform to semver best practices, you'd have to bump the major version. If you want to avoid this, I'm happy to put the argument back in place.

**Comment by m-reuter** [comment]
I also think we should drop it. And if we do it consistently across the solver I think a major release makes sense (anyway has been a while since the last).  Thanks for you help!

**Pull request merged**
