### PR TITLE
CMake improvements

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by m-reuter** [comment]
Thanks. About the examples: There is nothing to build here without examples. The library consists only of headers. We may want to put everything except the install target inside the IF EXAMPLES block? There is no need to check for libraries if EXAMPLES is off.

Also about the install rule for headers. I think we also need the .h files from all the other include directories under examples/matrices example/matprod and examples/areig?

**Comment by jschueller** [comment]
- Ok for the examples I changed the strategy : they're built by "make examples" and not by default.
- Aren't the headers in examples/ specific to the examples ?

**Comment by m-reuter** [comment]
The example headers contain some nice utility (e.g. the class Solution to print results, several simple matrices for testing, wrapper functions etc.). I think it makes sense to make them available via install. (Can you do that)? Then the travis file needs to be changed to "make examples" and maybe we want to run "make install" also for testing on travis. 
Finally, I plan to switch to explicitly listing each file in CMakeLists.txt instead of the globbing everwhere. That way cmake will know when to re-run (if a file name gets changed or file added/removed). That does not need to be part of this merge, though.

**Comment by jschueller** [comment]
I updated the Travis file.
You mean install all the headers ?

**Comment by m-reuter** [comment]
Yes, would be great.

**Comment by jschueller** [comment]
Ok, done (Travis updated too).

**Comment by m-reuter** [comment]
For some reason, the travis mac build still fails. Probably some of the mac specific fortran libraries are not added to the example target?
Also, some systems (like my centos) don't need and don't have the quadmath library, so we should not fail if not found.

**Comment by m-reuter** [comment]
Oh, also about the install naming. At some point we decided to call the project arpackpp, should we install to that dir instead of ++ ? Or do you know of existing dependencies that expect arpack++ ?

**Comment by jschueller** [comment]
I'll try to fix that tomorrow.
About the naming, I mimic Debian which provide them under /usr/include/arpack++:
https://packages.debian.org/jessie/amd64/libarpack++2-dev/filelist
But that doesn't mean it cannot change, names that contains '+' are not always allowed.

**Comment by m-reuter** [comment]
This should fix it:
 `SET (GFORTRAN_LIB ${GCC_EXT_LIB})`
should be 
`SET (GFORTRAN_LIB ${GFORTRAN_LIB} ${QUADMATH_LIB} ${GCC_EXT_LIB})`
thats where the fortran libs get dropped.
Also moving the block with
`MESSAGE(STATUS "quadmath is required but could not be found")
  SET(ABORT_CONFIG TRUE)`
back into the apple block should fix old centos. It will show as not found but still continue. 

Naming: I'd prefer arpackpp. That will make it clear that this is not the old arpack++ library.

**Comment by jschueller** [comment]
Ok, fixed. 
I also installed to include/arpackpp instead of include/arpack++ then.

**Pull request merged**
